// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvgrctozdikdytdecsst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2Z3JjdG96ZGlrZHl0ZGVjc3N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MzUzNjQsImV4cCI6MjA2MTExMTM2NH0.hVLCSmScyT-V4gfinxEkx6ZuufFcSTF_WFS0-EtTWME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);